namespace HavenoSharp.Models;

public enum FormId
{
    BLOCK_CHAINS,
    REVOLUT,
    SEPA,
    SEPA_INSTANT,
    TRANSFERWISE,
    ZELLE,
    SWIFT,
    F2F,
    STRIKE,
    MONEY_GRAM,
    FASTER_PAYMENTS,
    UPHOLD,
    PAXUM,
    PAY_BY_MAIL,
    CASH_AT_ATM,
    AUSTRALIA_PAYID,
    CASH_APP,
    PAYPAL,
    VENMO,
    PAYSAFE,
    WECHAT_PAY,
    ALI_PAY,
    SWISH,
    TRANSFERWISE_USD,
    AMAZON_GIFT_CARD,
    ACH_TRANSFER,
    INTERAC_E_TRANSFER,
    US_POSTAL_MONEY_ORDER
}
